### ISSUE TITLE
Error while loggin in the libbyapp

### ISSUE THREAD

**Issue by JaegerMaster** [jdalbey/libbyfetch#4] opened 2024-11-14 13:19 UTC
The error is thrown up while initiatizing and loggin in:

> Initializing LibbyApp
> Reading library card configuration file.
> Loading library page for 'wccls'
> Starting signin with your library card.
> Card Number set successfully.
> 'Next' Button clicked.
> PIN entered.
> An error occurred finding Sign In button: Message: 
> Stacktrace:
> #0 0x5868b79094ca <unknown>
...
Python Version: 3.10.12

**Comment by jdalbey** [comment] 2024-11-14 21:02
Duplicate of #3. This issue is already reported as https://github.com/jdalbey/libbyfetch/issues/3.  Please check there for updates on its status.

**Comment by jdalbey** [comment] 2024-11-14 21:05
Closing as duplicate of #3

**Closed as completed by jdalbey** 2024-11-14 21:05 UTC
Labels: duplicate
